Do not delete required packages without versions
These are assumed to exist later in the resolver process.

On the main branch the added test case fails with:

```
  Got exception outside of a @test
  KeyError: key :PkgA not found
  Stacktrace:
    [1] getindex(h::Dict{Symbol, Int64}, key::Symbol)
      @ Base ./dict.jl:478
    [2] sat_assume (repeats 2 times)
      @ ~/JuliaPkgs/Pkg.jl/Resolver.jl/src/SAT.jl:124 [inlined]
    [3] #sat_assume##0
      @ ~/JuliaPkgs/Pkg.jl/Resolver.jl/src/SAT.jl:127 [inlined]
    [4] foreach
      @ ./abstractarray.jl:3202 [inlined]
    [5] sat_assume
      @ ~/JuliaPkgs/Pkg.jl/Resolver.jl/src/SAT.jl:126 [inlined]
    [6] is_satisfiable(sat::Resolver.SAT{Symbol, Symbol}, reqs::Vector{Symbol})
```